"""empty message

Revision ID: 8575d78f3d42
Revises: 328d7cf98873
Create Date: 2017-08-12 16:28:36.342384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8575d78f3d42'
down_revision = '328d7cf98873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
